---
- hosts: all
  become: yes
  remote_user: "{{ user }}"
  roles:
    - git
    - files
    - neovim
    - fish
  post_tasks:
    - name: Remove config files
      ansible.builtin.file:
        path: /tmp/ansible_dl
        state: absent
