---
- name: Install Neovim
  ansible.builtin.package:
    name: neovim
    state: present

- name: Install Vundle
  ansible.builtin.git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: "/home/{{ user }}/.vim/bundle/Vundle.vim"

- name: Configure Vundle
  ansible.builtin.shell: nvim +PluginInstall +qall --headless
