---
- name: Install Git
  ansible.builtin.package:
    name: git
    state: present

- name: Retrieve config files from GitHub
  ansible.builtin.git:
    repo: https://github.com/PierrickF/dotfiles.git
    dest: /tmp/ansible_dl
